### PR TITLE
Quick fix for a bug breaking the submissions gallery.

### LINKED ISSUE #125: Uploaded image isn't showing up in the RB Submission Gallery
_BUG_
-------------------
**Current Behavior**
On https://next.dosomething.org/campaigns/teens-for-jeans/action when trying to RB, the uploaded image doesn't show up after hitting "Submit"

**Desired Behavior**
When you submit a photo and other RB info, it shows up under the uplaoder

**Steps to Replicate**
1. Go to https://next.dosomething.org/campaigns/teens-for-jeans/action
2. Try to upload a RB -- fill in all the info
3. It doesn't load

**Why This Matters**
So folks can see their RBs in the submission gallery

**Relevant Screenshots + Links**
screen shot 2017-04-05 at 5 31 35 pm

### PR DESCRIPTION
**Pull request by weerd**
This PR fixes a bug that is currently breaking the submissions gallery. The analytics related code tries to retrieve data from Reportback Items, however the RB items in the submission gallery do not contain reactions or parent reportback information. This just adds a fallback in case that data is not present.

Fixes #125

### CODE REVIEW

**Comment by weerd** [comment]
We're moving quick! Bound to happen 😬

File: resources/assets/components/ReportbackItem/index.js [hunk 1]
```diff
@@ -8,9 +8,9 @@ function getMetadataFromProps(props) {
   return {
     itemId: props.id,
     quantity: props.quantity,
-    totalReactions: props.reaction.total,
-    reportbackId: props.reportback.id,
-    reportbackUser: props.reportback.user,
+    totalReactions: props.reaction ? props.reaction.total : null,
+    reportbackId: props.reportback ? props.reportback.id : null,
```
Comment (DFurnes) [inline resources/assets/components/ReportbackItem/index.js]: Wait, sorry post-merge question –– there isn't ever a `props.reportback` is there?

Comment (deadlybutter) [inline resources/assets/components/ReportbackItem/index.js]: I added that for the data tracking!
